import React, { useState, useEffect } from 'react';
import { Lightbulb, Sparkles, Send, CheckCircle2, ShieldCheck, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { GuardianIdea, PersonaRole } from '../types';
import { fetchIdeas } from '../lib/dataService';

interface IdeasProps {
  activePersona?: PersonaRole;
}

export const Ideas: React.FC<IdeasProps> = ({ activePersona = 'Trader' }) => {
  const navigate = useNavigate();
  const [ideas, setIdeas] = useState<GuardianIdea[]>([]);
  const [sendingId, setSendingId] = useState<string | null>(null);

  useEffect(() => {
    fetchIdeas().then((data) => setIdeas(data));
  }, []);

  const handleSendToBlotter = async (ideaId: string) => {
    setSendingId(ideaId);
    try {
      const response = await fetch(`/api/ideas/${ideaId}/send-to-blotter`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ traderId: 'TRD-8821', traderName: 'Alex Vance' }),
      });
      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          navigate('/trade');
          return;
        }
      }
    } catch (e) {
      console.warn('[Ideas] Backend send-to-blotter API unavailable, redirecting to Trade blotter');
    } finally {
      setSendingId(null);
    }
    navigate('/trade');
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="border-b border-slate-800 pb-4">
        <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2">
          <Lightbulb className="h-5 w-5 text-amber-400" />
          <span>Module 6: Guardian-Approved Idea Generator</span>
        </h1>
        <p className="text-xs text-slate-400">
          Opportunities generated by backend engines, pre-screened against GDPR consent scopes & MiFID II suitability rules.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {ideas.map((idea,i) => (
          <div
            key={i}
            className="rounded-2xl border border-[#1F2937] bg-[#0F1115] p-5 shadow-xl flex flex-col justify-between space-y-4 hover:border-amber-500/40 transition-all"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between border-b border-[#1F2937] pb-3">
                <span className="font-mono text-xs font-bold text-amber-400">{idea.id}</span>
                <span className="flex items-center gap-1 rounded bg-emerald-500/20 px-2 py-0.5 text-[10px] font-mono font-bold text-emerald-400 border border-emerald-500/30">
                  <ShieldCheck className="h-3 w-3" />
                  PRE-SCREENED ✓
                </span>
              </div>

              <div>
                <span className="text-[10px] font-mono uppercase text-slate-400 block">{idea.assetClass} | Client: {idea.clientName}</span>
                <h3 className="text-base font-bold text-slate-100 mt-0.5">{idea.title}</h3>
              </div>

              <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                <div className="rounded-lg border border-[#1F2937] bg-[#090A0C] p-2.5">
                  <span className="text-slate-400 text-[10px] block">Expected Alpha</span>
                  <span className="text-emerald-400 font-bold text-sm">+{idea.expectedAlphaBps} bps</span>
                </div>
                <div className="rounded-lg border border-[#1F2937] bg-[#090A0C] p-2.5">
                  <span className="text-slate-400 text-[10px] block">Sharpe / Return</span>
                  <span className="text-indigo-400 font-bold text-sm">{idea.riskAdjustedReturn}</span>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed bg-[#090A0C] p-3 rounded-xl border border-[#1F2937]">
                {idea.justification}
              </p>
            </div>

            <button
              onClick={() => handleSendToBlotter(idea.id)}
              disabled={sendingId === idea.id}
              className="w-full flex items-center justify-center gap-2 rounded-xl bg-amber-500 py-2.5 text-xs font-bold text-slate-950 hover:bg-amber-400 transition-colors disabled:opacity-50"
            >
              <Send className="h-4 w-4" />
              <span>{sendingId === idea.id ? 'Drafting Order...' : 'Send to Blotter (Create Order)'}</span>
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
